name: ✨ Feature Request
description: Suggest a new feature or enhancement for SwiftIntelligence
title: "[FEATURE] "
labels: ["enhancement", "needs-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving SwiftIntelligence! ✨
        Please provide detailed information about your feature request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature you want to request
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: This feature would solve the problem of...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: I would like the feature to work by...
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Target Module
      description: Which SwiftIntelligence module should this feature be added to?
      options:
        - Core
        - NLP (Natural Language Processing)
        - Vision
        - Speech
        - ML (Machine Learning)
        - Privacy
        - Network
        - Cache
        - Metrics
        - Reasoning
        - Image Generation
        - visionOS
        - New module
        - Cross-module
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New AI/ML capability
        - Performance improvement
        - Developer experience enhancement
        - New API/interface
        - Platform support
        - Integration with external service
        - Documentation improvement
        - Testing/debugging tool
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Important for my use case
        - Medium - Would be nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. As a developer, I want to...
        2. When building an AI app, I need to...
        3. For better performance, I would like to...
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: Proposed API Design
      description: How would you like the API to look? (Optional but helpful)
      render: swift
      placeholder: |
        // Example API design
        let feature = NewFeature()
        let result = try await feature.performAction(with: parameters)
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Are there any alternative solutions or workarounds you've considered?
      placeholder: I've considered... but it doesn't work because...
    validations:
      required: false

  - type: dropdown
    id: platform-support
    attributes:
      label: Platform Support
      description: Which platforms should this feature support?
      multiple: true
      options:
        - iOS
        - macOS
        - watchOS
        - tvOS
        - visionOS
        - All platforms
    validations:
      required: true

  - type: textarea
    id: implementation-details
    attributes:
      label: Implementation Considerations
      description: Any thoughts on implementation details, dependencies, or constraints?
      placeholder: This might require... or could be challenging because...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples
      placeholder: Add any other context, links, or screenshots here
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I searched for existing feature requests and didn't find a duplicate
          required: true
        - label: This feature aligns with SwiftIntelligence's AI/ML focus
          required: true
        - label: I'm willing to provide additional clarification if needed
          required: true
        - label: I would be interested in contributing to this feature's implementation
          required: false