name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

env:
  SWIFT_VERSION: 5.9

jobs:
  # Swift Package Tests
  test-swift-package:
    name: Test Swift Package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-13]
        swift-version: [5.9]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Swift ${{ matrix.swift-version }}
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift-version }}
    
    - name: Cache Swift Package Manager
      uses: actions/cache@v3
      with:
        path: |
          .build
          ~/.cache/org.swift.swiftpm
        key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Build Debug
      run: swift build --configuration debug
    
    - name: Build Release
      run: swift build --configuration release
    
    - name: Run Tests
      run: swift test --enable-code-coverage
    
    - name: Generate Code Coverage
      run: |
        xcrun llvm-cov export -format="lcov" \
          .build/debug/SwiftIntelligencePackageTests.xctest/Contents/MacOS/SwiftIntelligencePackageTests \
          -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
      continue-on-error: true
    
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage.lcov
        flags: unittests
        name: codecov-umbrella
      continue-on-error: true

  # iOS Platform Tests
  test-ios:
    name: Test iOS
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.1'
    
    - name: Cache Xcode Build
      uses: actions/cache@v3
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-xcode-${{ hashFiles('Package.swift') }}
        restore-keys: |
          ${{ runner.os }}-xcode-
    
    - name: Build and Test iOS
      run: |
        xcodebuild -scheme SwiftIntelligence \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
          -enableCodeCoverage YES \
          build test
      continue-on-error: true

  # macOS Platform Tests  
  test-macos:
    name: Test macOS
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.1'
    
    - name: Build and Test macOS
      run: |
        xcodebuild -scheme SwiftIntelligence \
          -destination 'platform=macOS' \
          -enableCodeCoverage YES \
          build test

  # Linting and Code Quality
  lint:
    name: Lint and Code Quality
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: 5.9
    
    - name: Cache SwiftLint
      uses: actions/cache@v3
      with:
        path: /usr/local/bin/swiftlint
        key: ${{ runner.os }}-swiftlint
    
    - name: Install SwiftLint
      run: |
        if ! command -v swiftlint &> /dev/null; then
          brew install swiftlint
        fi
    
    - name: SwiftLint
      run: swiftlint lint --reporter github-actions-logging
      continue-on-error: true
    
    - name: Check Swift Formatting
      run: |
        swift-format lint --recursive Sources Tests Examples
      continue-on-error: true

  # Documentation
  docs:
    name: Documentation
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: 5.9
    
    - name: Build Documentation
      run: |
        swift package generate-documentation --target SwiftIntelligence
      continue-on-error: true

  # Security and Dependencies
  security:
    name: Security Scan
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Run Security Audit
      run: |
        # Check for security vulnerabilities in dependencies
        swift package dump-package | jq -r '.dependencies[].url' | while read url; do
          echo "Checking dependency: $url"
        done
      continue-on-error: true
    
    - name: Check for Sensitive Data
      run: |
        # Check for potential sensitive data in code
        grep -r --exclude-dir=.git --exclude-dir=.build \
          -E "(password|secret|key|token|api)" . || true
      continue-on-error: true

  # Performance Benchmarks
  performance:
    name: Performance Benchmarks
    runs-on: macos-14
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: 5.9
    
    - name: Run Performance Tests
      run: |
        swift test --filter PerformanceTests
      continue-on-error: true
    
    - name: Benchmark Results
      run: |
        echo "Performance benchmark completed"
        # Add performance metrics collection here
      continue-on-error: true

  # Multi-platform Build Matrix
  build-matrix:
    name: Build Matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-13]
        configuration: [debug, release]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: 5.9
    
    - name: Build ${{ matrix.configuration }}
      run: swift build --configuration ${{ matrix.configuration }}
    
    - name: Archive Build Artifacts
      if: matrix.configuration == 'release'
      run: |
        mkdir -p artifacts
        cp -r .build/release artifacts/
      continue-on-error: true
    
    - name: Upload Build Artifacts
      if: matrix.configuration == 'release'
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts-${{ matrix.os }}
        path: artifacts/
        retention-days: 30
      continue-on-error: true

  # Integration Test Status
  integration-status:
    name: Integration Status
    runs-on: macos-14
    needs: [test-swift-package, test-ios, test-macos, lint, docs, security]
    if: always()
    
    steps:
    - name: Check Integration Results
      run: |
        echo "Test Swift Package: ${{ needs.test-swift-package.result }}"
        echo "Test iOS: ${{ needs.test-ios.result }}"
        echo "Test macOS: ${{ needs.test-macos.result }}"
        echo "Lint: ${{ needs.lint.result }}"
        echo "Docs: ${{ needs.docs.result }}"
        echo "Security: ${{ needs.security.result }}"
        
        if [[ "${{ needs.test-swift-package.result }}" == "success" ]]; then
          echo "✅ Core framework tests passed"
        else
          echo "❌ Core framework tests failed"
        fi
        
        echo "🚀 SwiftIntelligence CI Pipeline Complete"