name: Deploy Documentation

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v6

      - name: Build Documentation
        run: bash Scripts/build-docs.sh ./docs

      - name: Setup Pages
        uses: actions/configure-pages@v6
        with:
          enablement: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
